### ISSUE TITLE
License type, please?

### ISSUE THREAD

**Issue by walakang** [shidil/drello#1]
i find this to be a nice piece of work to study, But can't find your licensing choice anywhere, and Github does not include one by default.

So, I know, it's a quite a long time since you worked on it, but, would you sir  please add one explicit license definition to make things transparent on this topic too?

I'd appreciate your kind response.

**Comment by shidil** [comment]
Hi @walakang Thanks for checkout out, and informing about the lack of license file. As you can see this was created a long time ago.

Please check the [LICENSE](https://github.com/shidil/drello/blob/master/LICENSE).
